---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: go-web-app
  template: 
    metadata:
      name: go-web-app
      labels:
        app: go-web-app
    spec:
      containers:
      - name: go-web-app
        image: asishdevops/go-web-app
        ports:
          - containerPort: 8080
---
